version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: blog1-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db

  post-service:
    build:
      context: ./post-service # Adjust for Dockerfile location
    container_name: post-service
    restart: always
    ports:
      - "5353:8080" # Map the Go app's port
    environment:
      # Pass environment variables or reference .env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

  search-service:
    build:
      context: ./search-service
    container_name: blog-search-service
    environment:
      - NODE_ENV=production
    ports:
      - "3636:3000"
    depends_on:
      - db

volumes:
  db_data:
